"""add_assignments_and_resources

Revision ID: 261402717dc7
Revises: 496884a4b04a
Create Date: 2026-07-26 16:57:31.389689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '261402717dc7'
down_revision: Union[str, Sequence[str], None] = '496884a4b04a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('instructions', sa.String(length=500), nullable=True),
    sa.Column('max_marks', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attachment_bucket', sa.String(length=100), nullable=True),
    sa.Column('attachment_path', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['edupulse.classes.id'], name=op.f('fk_assignments_class_id_classes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['edupulse.subjects.id'], name=op.f('fk_assignments_subject_id_subjects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['edupulse.teacher_profiles.id'], name=op.f('fk_assignments_teacher_id_teacher_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assignments')),
    schema='edupulse'
    )
    op.create_index(op.f('ix_edupulse_assignments_class_id'), 'assignments', ['class_id'], unique=False, schema='edupulse')
    op.create_index(op.f('ix_edupulse_assignments_id'), 'assignments', ['id'], unique=False, schema='edupulse')
    op.create_index(op.f('ix_edupulse_assignments_subject_id'), 'assignments', ['subject_id'], unique=False, schema='edupulse')
    op.create_index(op.f('ix_edupulse_assignments_teacher_id'), 'assignments', ['teacher_id'], unique=False, schema='edupulse')
    op.create_table('learning_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('file_bucket', sa.String(length=100), nullable=False),
    sa.Column('file_path', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['edupulse.subjects.id'], name=op.f('fk_learning_resources_subject_id_subjects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['edupulse.teacher_profiles.id'], name=op.f('fk_learning_resources_teacher_id_teacher_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_resources')),
    schema='edupulse'
    )
    op.create_index(op.f('ix_edupulse_learning_resources_id'), 'learning_resources', ['id'], unique=False, schema='edupulse')
    op.create_index(op.f('ix_edupulse_learning_resources_subject_id'), 'learning_resources', ['subject_id'], unique=False, schema='edupulse')
    op.create_index(op.f('ix_edupulse_learning_resources_teacher_id'), 'learning_resources', ['teacher_id'], unique=False, schema='edupulse')
    op.create_table('assignment_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.String(length=500), nullable=True),
    sa.Column('file_bucket', sa.String(length=100), nullable=True),
    sa.Column('file_path', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['edupulse.assignments.id'], name=op.f('fk_assignment_submissions_assignment_id_assignments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['edupulse.student_profiles.id'], name=op.f('fk_assignment_submissions_student_id_student_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assignment_submissions')),
    schema='edupulse'
    )
    op.create_index(op.f('ix_edupulse_assignment_submissions_assignment_id'), 'assignment_submissions', ['assignment_id'], unique=False, schema='edupulse')
    op.create_index(op.f('ix_edupulse_assignment_submissions_id'), 'assignment_submissions', ['id'], unique=False, schema='edupulse')
    op.create_index(op.f('ix_edupulse_assignment_submissions_student_id'), 'assignment_submissions', ['student_id'], unique=False, schema='edupulse')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_edupulse_assignment_submissions_student_id'), table_name='assignment_submissions', schema='edupulse')
    op.drop_index(op.f('ix_edupulse_assignment_submissions_id'), table_name='assignment_submissions', schema='edupulse')
    op.drop_index(op.f('ix_edupulse_assignment_submissions_assignment_id'), table_name='assignment_submissions', schema='edupulse')
    op.drop_table('assignment_submissions', schema='edupulse')
    op.drop_index(op.f('ix_edupulse_learning_resources_teacher_id'), table_name='learning_resources', schema='edupulse')
    op.drop_index(op.f('ix_edupulse_learning_resources_subject_id'), table_name='learning_resources', schema='edupulse')
    op.drop_index(op.f('ix_edupulse_learning_resources_id'), table_name='learning_resources', schema='edupulse')
    op.drop_table('learning_resources', schema='edupulse')
    op.drop_index(op.f('ix_edupulse_assignments_teacher_id'), table_name='assignments', schema='edupulse')
    op.drop_index(op.f('ix_edupulse_assignments_subject_id'), table_name='assignments', schema='edupulse')
    op.drop_index(op.f('ix_edupulse_assignments_id'), table_name='assignments', schema='edupulse')
    op.drop_index(op.f('ix_edupulse_assignments_class_id'), table_name='assignments', schema='edupulse')
    op.drop_table('assignments', schema='edupulse')
    # ### end Alembic commands ###
