"""002_authentication_domain

Revision ID: 496884a4b04a
Revises: f19cdf95d9a8
Create Date: 2026-07-24 21:25:34.001067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '496884a4b04a'
down_revision: Union[str, Sequence[str], None] = 'f19cdf95d9a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_years',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_academic_years')),
    schema='edupulse'
    )
    op.create_index(op.f('ix_edupulse_academic_years_id'), 'academic_years', ['id'], unique=False, schema='edupulse')
    op.create_index(op.f('ix_edupulse_academic_years_name'), 'academic_years', ['name'], unique=True, schema='edupulse')
    op.create_table('calendar_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('is_holiday', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calendar_events')),
    schema='edupulse'
    )
    op.create_index(op.f('ix_edupulse_calendar_events_id'), 'calendar_events', ['id'], unique=False, schema='edupulse')
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('grade', sa.String(length=20), nullable=True),
    sa.Column('section', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_classes')),
    schema='edupulse'
    )
    op.create_index(op.f('ix_edupulse_classes_id'), 'classes', ['id'], unique=False, schema='edupulse')
    op.create_index(op.f('ix_edupulse_classes_name'), 'classes', ['name'], unique=True, schema='edupulse')
    op.create_table('grade_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('min_score', sa.Integer(), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grade_mappings')),
    schema='edupulse'
    )
    op.create_index(op.f('ix_edupulse_grade_mappings_id'), 'grade_mappings', ['id'], unique=False, schema='edupulse')
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    schema='edupulse'
    )
    op.create_index(op.f('ix_edupulse_roles_id'), 'roles', ['id'], unique=False, schema='edupulse')
    op.create_index(op.f('ix_edupulse_roles_name'), 'roles', ['name'], unique=True, schema='edupulse')
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sections')),
    schema='edupulse'
    )
    op.create_index(op.f('ix_edupulse_sections_id'), 'sections', ['id'], unique=False, schema='edupulse')
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subjects')),
    schema='edupulse'
    )
    op.create_index(op.f('ix_edupulse_subjects_code'), 'subjects', ['code'], unique=True, schema='edupulse')
    op.create_index(op.f('ix_edupulse_subjects_id'), 'subjects', ['id'], unique=False, schema='edupulse')
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_settings')),
    schema='edupulse'
    )
    op.create_index(op.f('ix_edupulse_system_settings_id'), 'system_settings', ['id'], unique=False, schema='edupulse')
    op.create_index(op.f('ix_edupulse_system_settings_key'), 'system_settings', ['key'], unique=True, schema='edupulse')
    op.create_table('timetable_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.String(length=10), nullable=False),
    sa.Column('end_time', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['edupulse.classes.id'], name=op.f('fk_timetable_slots_class_id_classes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['edupulse.subjects.id'], name=op.f('fk_timetable_slots_subject_id_subjects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_timetable_slots')),
    schema='edupulse'
    )
    op.create_index(op.f('ix_edupulse_timetable_slots_class_id'), 'timetable_slots', ['class_id'], unique=False, schema='edupulse')
    op.create_index(op.f('ix_edupulse_timetable_slots_id'), 'timetable_slots', ['id'], unique=False, schema='edupulse')
    op.create_index(op.f('ix_edupulse_timetable_slots_subject_id'), 'timetable_slots', ['subject_id'], unique=False, schema='edupulse')
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['edupulse.roles.id'], name=op.f('fk_users_role_id_roles'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    schema='edupulse'
    )
    op.create_index(op.f('ix_edupulse_users_email'), 'users', ['email'], unique=True, schema='edupulse')
    op.create_index(op.f('ix_edupulse_users_id'), 'users', ['id'], unique=False, schema='edupulse')
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('content', sa.String(length=500), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['edupulse.users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
    schema='edupulse'
    )
    op.create_index(op.f('ix_edupulse_notifications_id'), 'notifications', ['id'], unique=False, schema='edupulse')
    op.create_index(op.f('ix_edupulse_notifications_user_id'), 'notifications', ['user_id'], unique=False, schema='edupulse')
    op.create_table('parent_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['edupulse.users.id'], name=op.f('fk_parent_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parent_profiles')),
    schema='edupulse'
    )
    op.create_index(op.f('ix_edupulse_parent_profiles_id'), 'parent_profiles', ['id'], unique=False, schema='edupulse')
    op.create_index(op.f('ix_edupulse_parent_profiles_user_id'), 'parent_profiles', ['user_id'], unique=True, schema='edupulse')
    op.create_table('student_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('roll_number', sa.String(length=50), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('guardian_name', sa.String(length=100), nullable=True),
    sa.Column('guardian_phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['edupulse.classes.id'], name=op.f('fk_student_profiles_class_id_classes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['edupulse.users.id'], name=op.f('fk_student_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_profiles')),
    schema='edupulse'
    )
    op.create_index(op.f('ix_edupulse_student_profiles_class_id'), 'student_profiles', ['class_id'], unique=False, schema='edupulse')
    op.create_index(op.f('ix_edupulse_student_profiles_id'), 'student_profiles', ['id'], unique=False, schema='edupulse')
    op.create_index(op.f('ix_edupulse_student_profiles_user_id'), 'student_profiles', ['user_id'], unique=True, schema='edupulse')
    op.create_table('teacher_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['edupulse.users.id'], name=op.f('fk_teacher_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teacher_profiles')),
    schema='edupulse'
    )
    op.create_index(op.f('ix_edupulse_teacher_profiles_id'), 'teacher_profiles', ['id'], unique=False, schema='edupulse')
    op.create_index(op.f('ix_edupulse_teacher_profiles_user_id'), 'teacher_profiles', ['user_id'], unique=True, schema='edupulse')
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('date_earned', sa.Date(), nullable=False),
    sa.Column('badge_name', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['edupulse.student_profiles.id'], name=op.f('fk_achievements_student_id_student_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_achievements')),
    schema='edupulse'
    )
    op.create_index(op.f('ix_edupulse_achievements_id'), 'achievements', ['id'], unique=False, schema='edupulse')
    op.create_index(op.f('ix_edupulse_achievements_student_id'), 'achievements', ['student_id'], unique=False, schema='edupulse')
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('hours_spent', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['edupulse.student_profiles.id'], name=op.f('fk_activities_student_id_student_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activities')),
    schema='edupulse'
    )
    op.create_index(op.f('ix_edupulse_activities_id'), 'activities', ['id'], unique=False, schema='edupulse')
    op.create_index(op.f('ix_edupulse_activities_student_id'), 'activities', ['student_id'], unique=False, schema='edupulse')
    op.create_table('ai_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('recommendation_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['edupulse.student_profiles.id'], name=op.f('fk_ai_recommendations_student_id_student_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_recommendations')),
    schema='edupulse'
    )
    op.create_index(op.f('ix_edupulse_ai_recommendations_id'), 'ai_recommendations', ['id'], unique=False, schema='edupulse')
    op.create_index(op.f('ix_edupulse_ai_recommendations_student_id'), 'ai_recommendations', ['student_id'], unique=False, schema='edupulse')
    op.create_table('growth_passports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('holistic_score', sa.Float(), nullable=False),
    sa.Column('growth_level', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['edupulse.student_profiles.id'], name=op.f('fk_growth_passports_student_id_student_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_growth_passports')),
    schema='edupulse'
    )
    op.create_index(op.f('ix_edupulse_growth_passports_id'), 'growth_passports', ['id'], unique=False, schema='edupulse')
    op.create_index(op.f('ix_edupulse_growth_passports_student_id'), 'growth_passports', ['student_id'], unique=True, schema='edupulse')
    op.create_table('shared_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('target_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['edupulse.parent_profiles.id'], name=op.f('fk_shared_goals_parent_id_parent_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['edupulse.student_profiles.id'], name=op.f('fk_shared_goals_student_id_student_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['edupulse.teacher_profiles.id'], name=op.f('fk_shared_goals_teacher_id_teacher_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shared_goals')),
    schema='edupulse'
    )
    op.create_index(op.f('ix_edupulse_shared_goals_id'), 'shared_goals', ['id'], unique=False, schema='edupulse')
    op.create_index(op.f('ix_edupulse_shared_goals_parent_id'), 'shared_goals', ['parent_id'], unique=False, schema='edupulse')
    op.create_index(op.f('ix_edupulse_shared_goals_student_id'), 'shared_goals', ['student_id'], unique=False, schema='edupulse')
    op.create_index(op.f('ix_edupulse_shared_goals_teacher_id'), 'shared_goals', ['teacher_id'], unique=False, schema='edupulse')
    op.create_table('student_parent_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['edupulse.parent_profiles.id'], name=op.f('fk_student_parent_mappings_parent_id_parent_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['edupulse.student_profiles.id'], name=op.f('fk_student_parent_mappings_student_id_student_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_parent_mappings')),
    schema='edupulse'
    )
    op.create_index(op.f('ix_edupulse_student_parent_mappings_id'), 'student_parent_mappings', ['id'], unique=False, schema='edupulse')
    op.create_index(op.f('ix_edupulse_student_parent_mappings_parent_id'), 'student_parent_mappings', ['parent_id'], unique=False, schema='edupulse')
    op.create_index(op.f('ix_edupulse_student_parent_mappings_student_id'), 'student_parent_mappings', ['student_id'], unique=False, schema='edupulse')
    op.create_table('study_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('plan_type', sa.String(length=50), nullable=False),
    sa.Column('plan_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['edupulse.student_profiles.id'], name=op.f('fk_study_plans_student_id_student_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_plans')),
    schema='edupulse'
    )
    op.create_index(op.f('ix_edupulse_study_plans_id'), 'study_plans', ['id'], unique=False, schema='edupulse')
    op.create_index(op.f('ix_edupulse_study_plans_student_id'), 'study_plans', ['student_id'], unique=False, schema='edupulse')
    op.create_table('teacher_class_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('is_homeroom', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['edupulse.classes.id'], name=op.f('fk_teacher_class_subjects_class_id_classes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['edupulse.subjects.id'], name=op.f('fk_teacher_class_subjects_subject_id_subjects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['edupulse.teacher_profiles.id'], name=op.f('fk_teacher_class_subjects_teacher_id_teacher_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teacher_class_subjects')),
    schema='edupulse'
    )
    op.create_index(op.f('ix_edupulse_teacher_class_subjects_class_id'), 'teacher_class_subjects', ['class_id'], unique=False, schema='edupulse')
    op.create_index(op.f('ix_edupulse_teacher_class_subjects_id'), 'teacher_class_subjects', ['id'], unique=False, schema='edupulse')
    op.create_index(op.f('ix_edupulse_teacher_class_subjects_subject_id'), 'teacher_class_subjects', ['subject_id'], unique=False, schema='edupulse')
    op.create_index(op.f('ix_edupulse_teacher_class_subjects_teacher_id'), 'teacher_class_subjects', ['teacher_id'], unique=False, schema='edupulse')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_edupulse_teacher_class_subjects_teacher_id'), table_name='teacher_class_subjects', schema='edupulse')
    op.drop_index(op.f('ix_edupulse_teacher_class_subjects_subject_id'), table_name='teacher_class_subjects', schema='edupulse')
    op.drop_index(op.f('ix_edupulse_teacher_class_subjects_id'), table_name='teacher_class_subjects', schema='edupulse')
    op.drop_index(op.f('ix_edupulse_teacher_class_subjects_class_id'), table_name='teacher_class_subjects', schema='edupulse')
    op.drop_table('teacher_class_subjects', schema='edupulse')
    op.drop_index(op.f('ix_edupulse_study_plans_student_id'), table_name='study_plans', schema='edupulse')
    op.drop_index(op.f('ix_edupulse_study_plans_id'), table_name='study_plans', schema='edupulse')
    op.drop_table('study_plans', schema='edupulse')
    op.drop_index(op.f('ix_edupulse_student_parent_mappings_student_id'), table_name='student_parent_mappings', schema='edupulse')
    op.drop_index(op.f('ix_edupulse_student_parent_mappings_parent_id'), table_name='student_parent_mappings', schema='edupulse')
    op.drop_index(op.f('ix_edupulse_student_parent_mappings_id'), table_name='student_parent_mappings', schema='edupulse')
    op.drop_table('student_parent_mappings', schema='edupulse')
    op.drop_index(op.f('ix_edupulse_shared_goals_teacher_id'), table_name='shared_goals', schema='edupulse')
    op.drop_index(op.f('ix_edupulse_shared_goals_student_id'), table_name='shared_goals', schema='edupulse')
    op.drop_index(op.f('ix_edupulse_shared_goals_parent_id'), table_name='shared_goals', schema='edupulse')
    op.drop_index(op.f('ix_edupulse_shared_goals_id'), table_name='shared_goals', schema='edupulse')
    op.drop_table('shared_goals', schema='edupulse')
    op.drop_index(op.f('ix_edupulse_growth_passports_student_id'), table_name='growth_passports', schema='edupulse')
    op.drop_index(op.f('ix_edupulse_growth_passports_id'), table_name='growth_passports', schema='edupulse')
    op.drop_table('growth_passports', schema='edupulse')
    op.drop_index(op.f('ix_edupulse_ai_recommendations_student_id'), table_name='ai_recommendations', schema='edupulse')
    op.drop_index(op.f('ix_edupulse_ai_recommendations_id'), table_name='ai_recommendations', schema='edupulse')
    op.drop_table('ai_recommendations', schema='edupulse')
    op.drop_index(op.f('ix_edupulse_activities_student_id'), table_name='activities', schema='edupulse')
    op.drop_index(op.f('ix_edupulse_activities_id'), table_name='activities', schema='edupulse')
    op.drop_table('activities', schema='edupulse')
    op.drop_index(op.f('ix_edupulse_achievements_student_id'), table_name='achievements', schema='edupulse')
    op.drop_index(op.f('ix_edupulse_achievements_id'), table_name='achievements', schema='edupulse')
    op.drop_table('achievements', schema='edupulse')
    op.drop_index(op.f('ix_edupulse_teacher_profiles_user_id'), table_name='teacher_profiles', schema='edupulse')
    op.drop_index(op.f('ix_edupulse_teacher_profiles_id'), table_name='teacher_profiles', schema='edupulse')
    op.drop_table('teacher_profiles', schema='edupulse')
    op.drop_index(op.f('ix_edupulse_student_profiles_user_id'), table_name='student_profiles', schema='edupulse')
    op.drop_index(op.f('ix_edupulse_student_profiles_id'), table_name='student_profiles', schema='edupulse')
    op.drop_index(op.f('ix_edupulse_student_profiles_class_id'), table_name='student_profiles', schema='edupulse')
    op.drop_table('student_profiles', schema='edupulse')
    op.drop_index(op.f('ix_edupulse_parent_profiles_user_id'), table_name='parent_profiles', schema='edupulse')
    op.drop_index(op.f('ix_edupulse_parent_profiles_id'), table_name='parent_profiles', schema='edupulse')
    op.drop_table('parent_profiles', schema='edupulse')
    op.drop_index(op.f('ix_edupulse_notifications_user_id'), table_name='notifications', schema='edupulse')
    op.drop_index(op.f('ix_edupulse_notifications_id'), table_name='notifications', schema='edupulse')
    op.drop_table('notifications', schema='edupulse')
    op.drop_index(op.f('ix_edupulse_users_id'), table_name='users', schema='edupulse')
    op.drop_index(op.f('ix_edupulse_users_email'), table_name='users', schema='edupulse')
    op.drop_table('users', schema='edupulse')
    op.drop_index(op.f('ix_edupulse_timetable_slots_subject_id'), table_name='timetable_slots', schema='edupulse')
    op.drop_index(op.f('ix_edupulse_timetable_slots_id'), table_name='timetable_slots', schema='edupulse')
    op.drop_index(op.f('ix_edupulse_timetable_slots_class_id'), table_name='timetable_slots', schema='edupulse')
    op.drop_table('timetable_slots', schema='edupulse')
    op.drop_index(op.f('ix_edupulse_system_settings_key'), table_name='system_settings', schema='edupulse')
    op.drop_index(op.f('ix_edupulse_system_settings_id'), table_name='system_settings', schema='edupulse')
    op.drop_table('system_settings', schema='edupulse')
    op.drop_index(op.f('ix_edupulse_subjects_id'), table_name='subjects', schema='edupulse')
    op.drop_index(op.f('ix_edupulse_subjects_code'), table_name='subjects', schema='edupulse')
    op.drop_table('subjects', schema='edupulse')
    op.drop_index(op.f('ix_edupulse_sections_id'), table_name='sections', schema='edupulse')
    op.drop_table('sections', schema='edupulse')
    op.drop_index(op.f('ix_edupulse_roles_name'), table_name='roles', schema='edupulse')
    op.drop_index(op.f('ix_edupulse_roles_id'), table_name='roles', schema='edupulse')
    op.drop_table('roles', schema='edupulse')
    op.drop_index(op.f('ix_edupulse_grade_mappings_id'), table_name='grade_mappings', schema='edupulse')
    op.drop_table('grade_mappings', schema='edupulse')
    op.drop_index(op.f('ix_edupulse_classes_name'), table_name='classes', schema='edupulse')
    op.drop_index(op.f('ix_edupulse_classes_id'), table_name='classes', schema='edupulse')
    op.drop_table('classes', schema='edupulse')
    op.drop_index(op.f('ix_edupulse_calendar_events_id'), table_name='calendar_events', schema='edupulse')
    op.drop_table('calendar_events', schema='edupulse')
    op.drop_index(op.f('ix_edupulse_academic_years_name'), table_name='academic_years', schema='edupulse')
    op.drop_index(op.f('ix_edupulse_academic_years_id'), table_name='academic_years', schema='edupulse')
    op.drop_table('academic_years', schema='edupulse')
    # ### end Alembic commands ###
