"use client";

import { useState, useEffect, useCallback } from "react";
import { PageHeader } from "@/components/layout/page-header";
import { AIInsightCard } from "@/components/cards/ai-insight-card";
import { SkeletonCard } from "@/components/common/skeleton";
import { ErrorState } from "@/components/common/states";
import { studentService } from "@/services/student.service";
import type { StudyPlanDTO } from "@/types/student.types";
import { Sparkles, CalendarCheck, RefreshCw } from "lucide-react";
import { toast } from "sonner";
import { formatDateTime } from "@/lib/utils";

export default function StudentStudyPlanPage() {
  const [studyPlan, setStudyPlan] = useState<StudyPlanDTO | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [isGenerating, setIsGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const fetchPlan = useCallback(async () => {
    setIsLoading(true);
    setError(null);
    try {
      const response = await studentService.getStudyPlan();
      if (response.success && response.data) {
        setStudyPlan(response.data);
      }
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : "Error fetching study plan");
    } finally {
      setIsLoading(false);
    }
  }, []);

  const handleRegenerate = async () => {
    setIsGenerating(true);
    try {
      const response = await studentService.createStudyPlan({
        target_focus: "Exam Preparation & Weak Concept Remediation",
        preferred_hours_per_day: 2.5,
      });
      if (response.success && response.data) {
        setStudyPlan(response.data);
        toast.success("New AI Study Plan generated!");
      } else {
        toast.error("Failed to generate plan");
      }
    } catch (err: unknown) {
      toast.error(err instanceof Error ? err.message : "Generation failed");
    } finally {
      setIsGenerating(false);
    }
  };

  useEffect(() => {
    fetchPlan();
  }, [fetchPlan]);

  return (
    <div className="space-y-6">
      <PageHeader
        title="AI Study Plan & Schedule"
        subtitle="Adaptive study recommendations generated by the AI Learning Engine"
        actions={
          <button
            onClick={handleRegenerate}
            disabled={isGenerating}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-md text-xs font-medium bg-[var(--primary)] text-white hover:bg-[var(--primary-hover)] disabled:opacity-50 transition-colors"
          >
            <RefreshCw size={13} className={isGenerating ? "animate-spin" : ""} />
            <span>{isGenerating ? "Generating..." : "Regenerate AI Plan"}</span>
          </button>
        }
      />

      {isLoading ? (
        <SkeletonCard />
      ) : error ? (
        <ErrorState title="Could not load study plan" message={error} onRetry={fetchPlan} />
      ) : studyPlan ? (
        <div className="space-y-6">
          <AIInsightCard
            title={`AI Personal Plan (${studyPlan.plan_type})`}
            analysis={(() => {
              const planData = studyPlan.plan_data as any;
              if (typeof planData === "string") return planData;
              if (planData?.narrative) return String(planData.narrative);
              const focusList = Array.isArray(planData?.focus_areas) ? planData.focus_areas : [];
              const scheduleList = Array.isArray(planData?.schedule) ? planData.schedule : [];
              return (
                `### 🎯 Focus Areas\n` +
                focusList.map((f: string) => `- ${f}`).join("\n") +
                `\n\n### 📅 Recommended Weekly Schedule\n` +
                scheduleList.map((s: any) => `- **${s.day}**: ${s.topic} (${s.duration}) — *${s.priority} Priority*`).join("\n")
              );
            })()}
            confidence={95}
          />

          <div className="p-5 rounded-lg border border-[var(--border)] bg-[var(--surface)] space-y-3">
            <h4 className="text-xs font-semibold text-[var(--text-primary)] uppercase tracking-wider flex items-center gap-2">
              <CalendarCheck size={14} className="text-[var(--primary)]" />
              Plan Metadata & Timestamp
            </h4>
            <div className="grid grid-cols-2 sm:grid-cols-3 gap-3 text-xs text-[var(--text-secondary)]">
              <div>
                <span className="text-[var(--text-muted)] block">Plan ID</span>
                <span className="font-mono text-[var(--text-primary)]">#{studyPlan.id}</span>
              </div>
              <div>
                <span className="text-[var(--text-muted)] block">Plan Type</span>
                <span className="font-medium text-[var(--text-primary)]">{studyPlan.plan_type}</span>
              </div>
              <div>
                <span className="text-[var(--text-muted)] block">Generated On</span>
                <span className="font-mono text-[var(--text-primary)]">{formatDateTime(studyPlan.created_at)}</span>
              </div>
            </div>
          </div>
        </div>
      ) : (
        <div className="p-8 text-center rounded-lg border border-[var(--border)] bg-[var(--surface)] space-y-3">
          <Sparkles size={24} className="mx-auto text-[var(--primary)]" />
          <h3 className="text-sm font-semibold text-[var(--text-primary)]">No Study Plan Active</h3>
          <p className="text-xs text-[var(--text-secondary)] max-w-sm mx-auto">
            Click the button below to generate your personalized AI study schedule based on your current learning health score.
          </p>
          <button
            onClick={handleRegenerate}
            disabled={isGenerating}
            className="px-4 py-2 rounded-md text-xs font-medium bg-[var(--primary)] text-white hover:bg-[var(--primary-hover)]"
          >
            Generate AI Study Plan
          </button>
        </div>
      )}
    </div>
  );
}
